#!/bin/bash

xsetroot -cursor_name left_ptr &

bspc monitor DVI-I-1 -d 7 8
bspc monitor HDMI-1 -d 1 2 3 4 5 6

xrandr --output DVI-I-1 --left-of HDMI-1

pkill polybar
polybar monitor -r &

pkill sxhkd
sxhkd & >> /dev/null
